from Calculator import *
from Calendar import *
from Camera import *
from Clock import *
from Contacts import *
from Email import *
from EverythingMe import *
from Facebook import *
from Ftu import *
from Gallery import *
from Marketplace import *
from Messages import *
from Music import *
from Settings import *
from Video import *
from Dialer import *
