from app_browser import *
from app_calculator import *
from app_calendar import *
from app_camera import *
from app_clock import *
from app_contacts import *
from app_email import *
from app_everythingMe import *
from app_facebook import *
from app_ftu import *
from app_gallery import *
from app_market import *
from app_messages import *
from app_settings import *
from app_video import *
from app_keyboard import *
from app_phone import *