import Browser
import Calculator
import Calendar
import Camera
import Clock
import Contacts
import Email
import EME
import Facebook
import FTU
import Gallery
import GLOBAL
import Home
import Market
import Messages
import Phone
import Settings
import Statusbar
import Video
import Keyboard