frame_locator                   = ("src", "camera")

capture_button           = ('id', 'capture-button')
thumbnail                = ('class name', 'thumbnail')
thumbnail_preview_marker = ('id', 'preview')
switch_source_btn        = ('id', 'switch-button')
capture_button_enabled   = ('css selector', '#capture-button:not([disabled])')
video_timer              = ('id', 'video-timer')
video_play_button        = ('xpath', "//button[@class='videoPlayerPlayButton']")
video_pause_button       = ('xpath', "//button[@class='videoPlayerPauseButton']")
gallery_button           = ("id", "gallery-button")
trash_icon               = ("id", "delete-button")
select_button           = ('id', 'select-button')
retake_button           = ('id', 'retake-button')
select_button           = ('id', 'select-button')
retake_button           = ('id', 'retake-button')