frame_locator = ('src', 'collection')
bookmark_frame_locator = ('src', 'bookmark')
here_check = ('id', 'shortcuts-items')
groups = ('id', "icongrid")
add_group_button = ("xpath", "//li[@class='shortcut add']")
remove_group_icon = ("xpath", "./span[@class='remove']")
loading_groups_message = ("id", "shortcuts-customize-loading")
apps_installed = ("xpath", "//ul[@id='evmeAppsList']/li[not(contains(@class,'cloud'))]")
apps_not_installed = ('css selector', "gaia-grid#grid div.icon.bookmark")
app_to_install = "//div[contains(@class, 'icon')]//span[text()='{}']/../.."
back_btn = ('id', 'button-clear')
connection_warning_msg = ("class name", "connection-message")
search_field = ("id", "search-q")
start_eme_icon = ("id", "evme-activation-icon")
# search_suggestions      = ('css selector', '#helper ul li[data-index]')
search_suggestions = ("xpath", "//div[@id='helper-header']//*[@id='helper-rapper']//li")
search_clear = ("id", "button-clear")
searching_spinner = ("class name", "loading-apps")
search_result_icon_xpath = "//li[@data-name='{}']"
search_result_area = ("id", "evmeApps")
app_installed_banner = ("id", "evmeBanner")

launched_activity_bar = ("id", "wrapper-activity-indicator")  # (in the top level frame)
launched_display_button_bar = ("id", "handler")
launched_button_bar = ("xpath", "//menu[@type='buttonbar']")  # (in the top level frame)
launched_button_back = ("id", "back-button")
launched_button_forward = ("id", "forward-button")
launched_button_reload = ("id", "reload-button")
launched_button_bookmark = ("id", "bookmark-button")
launched_button_close = ("id", "close-button")

launched_add_to_homescreen = ("xpath", "//*[@id='modal-dialog-select-one']//button")
add_to_home_screen_frame = ("src", "homescreen.gaiamobile.org/save-bookmark")
add_to_home_screen_btn = ("id", "bookmark-cloudapp")  # in add_to_home_screen_frame
add_to_top_of_collection_btn = ("id", "pin-cloudapp")
add_bookmark_btn = ('id', 'add-button')

app_canvas_title = ('xpath', "//div[@class='identification-overlay']//span[@class='title' and contains(text(), '{}')]")
bookmark_url = ('id', 'bookmark-url')