frame_locator = ('src', 'collection')
bookmark_frame_locator = ('src', 'bookmark')
search_frame_locator = ('src', 'search')
here_check = ('id', 'shortcuts-items')
groups = ('css selector', "gaia-grid#icons")
add_group_button = ("xpath", "//li[@class='shortcut add']")
remove_group_icon = ("xpath", "./span[@class='remove']")
loading_groups_message = ("id", "shortcuts-customize-loading")
apps_installed = ("xpath", "//ul[@id='evmeAppsList']/li[not(contains(@class,'cloud'))]")
apps_not_installed = ('css selector', "gaia-grid#grid div.icon.bookmark")
app_to_install = "//div[contains(@class, 'icon')]//span[text()='{}']/../.."
all_collections = ('css selector', 'div.icon.collection')
back_btn = ('id', 'button-clear')
search_field = ("css selector", "#search #search-input")
start_eme_icon = ("id", "evme-activation-icon")
# search_suggestions      = ('css selector', '#helper ul li[data-index]')
search_suggestions = ("xpath", "//div[@id='helper-header']//*[@id='helper-rapper']//li")
search_clear = ("id", "button-clear")
searching_spinner = ("class name", "loading-apps")
search_result_icon_xpath = "//li[@data-name='{}']"
search_result_area = ("id", "evmeApps")
app_installed_banner = ("id", "evmeBanner")

launched_activity_bar = ("id", "wrapper-activity-indicator")  # (in the top level frame)
launched_display_button_bar = ("id", "handler")
footer_navigation_bar = ('css selector', 'footer.navigation')
launched_button_back = ("css selector", ".back-button")
launched_button_forward = ("css selector", ".forward-button")
launched_button_reload = ("css selector", ".reload-button")
launched_button_bookmark = ("css selector", ".bookmark-button")
launched_button_close = ("css selector", ".close-button")

launched_add_to_homescreen = ("xpath", "//*[@id='modal-dialog-select-one']//button")
add_to_home_screen_frame = ("src", "homescreen.gaiamobile.org/save-bookmark")
add_to_home_screen_btn = ("id", "bookmark-cloudapp")  # in add_to_home_screen_frame
add_to_top_of_collection_btn = ("id", "pin-cloudapp")
add_bookmark_btn = ('id', 'add-button')

app_canvas_title = ('xpath', "//div[@class='identification-overlay']//span[@class='title' and contains(text(), '{}')]")
bookmark_url = ('id', 'bookmark-url')
bookmark_close = ('css selector', 'span.icon.icon-close')
bookmark_group_name = ('id', 'name')
add_bookmark_header = ('id', 'add-bookmark-header')
edit_bookmark_header = ('id', 'edit-bookmark-header')
bookmark_app_btn = ('css selector', '#modal-dialog-select-one #search')

game_content = ('id', 'game-content')

offline_message = ('id', 'offline-message')
suggestions_notice_confirm_btn = ('id', 'suggestions-notice-confirm')
