market_loading_icon     = ('css selector', 'div.loading-fragment')
frame_locator           = ("src","https://marketplace.firefox.com/")
search_query            = ('id', 'search-q')
featured_apps           = ('xpath', ".//*[@id='featured-home']/ul/li/a/canvas")
install_button          = ('css selector', '.button.product.install')
app_details_header      = ('xpath', '//h3')
confirm_install_button  = ('id', 'app-install-install-button')

search_results_area     = ('id', 'search-results')
search_results          = ('css selector', '#search-results li.item')
app_name                = ('xpath', '//h3')
author                  = ('css selector', '.author.lineclamp.vital')