frame_locator = ("src", "marketplace")
market_loading_icon = ('css selector', 'div.loading-fragment')
search_query = ('id', 'search-q')
featured_apps = ('xpath', ".//*[@id='featured-home']/ul/li/a/canvas")
install_button = ('css selector', '.button.product.install')
app_details_header = ('xpath', '//h3')
confirm_install_button = ('id', 'app-install-install-button')

search_results_area = ('id', 'search-results')
search_results = ('css selector', '#search-results li.item')
app_name = ('css selector', 'li.item.result div.info h3[itemprop=name]')
author = ('css selector', 'li.item.result div.author[itemprop=creator]')
