from OWDTestToolkit.utils.i18nsetup import I18nSetup
_ = I18nSetup(I18nSetup).setup()

status_bar_new = ('xpath', "//*[@id='statusbar-notification'][@data-unread='true']")
wifi = ('id', 'statusbar-wifi')
dataConn = ('css selector', '#statusbar-connections .statusbar-data')
dataConn = ('xpath', '//div[@id="statusbar-connections"]//div[contains(@class, "statusbar-data") and @aria-hidden="true"]')
bluetooth = ('id', 'statusbar-bluetooth')
airplane = ('id', 'statusbar-flight-mode')
signal_connected = ('xpath', '//div[@id="statusbar-connections"]//div[contains(@class, "statusbar-signal") and contains(@aria-label, "{}")]'.format(_("bars")))
hotspot = ("id", "statusbar-tethering")
network_activity = ("id", "statusbar-network-activity")
downloads = ("id", "statusbar-system-downloads")

clear_all_button = ('id', 'notification-clear')
toggle_wifi = ("id", "quick-settings-wifi")
toggle_dataconn = ("id", "quick-settings-data")
toggle_bluetooth = ("id", "quick-settings-bluetooth")
toggle_airplane = ("id", "quick-settings-airplane-mode")

settings_button = ("id", "quick-settings-full-app")
notification_toaster_detail = ("xpath", u"//div[@id='toaster-detail' and contains(text(),'{}')]")
notification_toaster_title = ("xpath", u"//div[@id='toaster-title' and contains(text(),'{}')]")
notification_statusbar_title = ('xpath', u'//div[@id="desktop-notifications-container"]/div[@class="notification"]//div[contains(text(), "{}")]/ancestor::div[1]')
notification_statusbar_detail = ('xpath', u'//div[@id="desktop-notifications-container"]/div[@class="notification"]/div[@class="detail" and contains(text(),"{}")]')
